- name: Check node master
  command: kubectl get nodes --selector=node-role.kubernetes.io/master -ojsonpath --template='{.items[].spec.taints}'
  register: kube_node_master

- name: Untaint node
  command: kubectl taint nodes --all node-role.kubernetes.io/master-
  when: kube_node_master.stdout.find('NoSchedule') != -1

- name: Check Flannel
  command: kubectl -nkube-system get daemonset
  register: kube_flannel

- name: Install Flannel
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  when: kube_flannel.stdout.find('flannel') == -1

- name: Deploy sample app
  command: kubectl create deployment hello-app --image=gcr.io/google-samples/hello-app:1.0

- name: Expose sample app
  command: kubectl expose deployment hello-app --type=NodePort --port=8080